# Generated by Django 4.0.3 on 2022-04-05 07:57

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=1000, unique=True)),
            ],
            options={
                'ordering': ['material'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('stock', models.PositiveIntegerField(default=1, help_text='Will Be Automatically Calculated', validators=[django.core.validators.MinValueValidator(0)])),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_of_product', to='offer.offer')),
                ('shop', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_of_product', to='shop.shop')),
            ],
            options={
                'ordering': ['edited'],
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=1000, unique=True)),
            ],
            options={
                'ordering': ['size'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='types/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('stock', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='variations/%Y/%m/%d/')),
                ('dimension_LxWxH', models.CharField(blank=True, help_text='(in centimeters (cms))', max_length=200, null=True)),
                ('date_first_available', models.DateField(auto_now_add=True, null=True)),
                ('manufacturer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, default='Mens', max_length=100, null=True)),
                ('manufacturer_address', models.CharField(blank=True, max_length=500, null=True)),
                ('packer_address', models.CharField(blank=True, max_length=500, null=True)),
                ('item_weight', models.FloatField(blank=True, help_text='(in grams (gms))', null=True)),
                ('net_quantity', models.IntegerField(blank=True, null=True)),
                ('included_components', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('generated_variation_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_of_variation', to='product.color')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_of_variation', to='product.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='product.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_of_variation', to='product.size')),
            ],
            options={
                'ordering': ['edited'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='products/default.jpg', upload_to='products/%Y/%m/%d/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_product', to='product.type'),
        ),
    ]
