# Generated by Django 4.0.3 on 2022-04-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i1', models.ImageField(blank=True, default='carousel_default/1.jpg', unique=True, upload_to='carousel/%Y/%m/%d/')),
                ('i2', models.ImageField(blank=True, default='carousel_default/2.jpg', unique=True, upload_to='carousel/%Y/%m/%d/')),
                ('i3', models.ImageField(blank=True, default='carousel_default/3.jpg', unique=True, upload_to='carousel/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_of_gallery', to='product.product')),
            ],
        ),
    ]
