# Generated by Django 4.0.3 on 2022-04-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=1000)),
                ('photo', models.ImageField(blank=True, default='shop/default.png', unique=True, upload_to='shop/%Y/%m/%d/')),
            ],
        ),
    ]
