# Generated by Django 4.0.3 on 2022-04-05 07:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('size', models.CharField(blank=True, max_length=1000)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('color', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_of_item', to='product.color')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_of_item', to='product.product')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variation_of_item', to='product.variation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
