# Generated by Django 4.0.3 on 2022-04-05 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_order_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('payment_method', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=1000)),
                ('zip', models.PositiveBigIntegerField()),
                ('phonenumber', models.PositiveBigIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('dispatched', models.BooleanField()),
                ('dispatched_timestamp', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField()),
                ('delivered_timestamp', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField()),
                ('cancelled', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(related_name='product_of_order', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
